### ISSUE TITLE
Small fixes needed

### ISSUE THREAD

**Issue by semisight** [leoschuler/gtag-mautic-initialization#1]
https://github.com/leoschuler/gtag-mautic-initialization/blob/50e16d7d404ff1db4454c62f5597964728b10ff8/template.tpl#L98

This should have `gtmOnSuccess` and `gtmOnFailure` passed in as arguments.

https://github.com/leoschuler/gtag-mautic-initialization/blob/50e16d7d404ff1db4454c62f5597964728b10ff8/metadata.yaml#L16

This line matches the `homepage`, and is unnecessary. Please remove.

**Comment by leoschuler** [comment]
my suggestion to the missing call gmtOnSuccess is:
```
if( data.consent_type == undefined ) {
  loadTag( data.gtmOnSuccess ,  data.gtmOnFailure );
} else if( isConsentGranted(data.consent_type) ) {
  loadTag( data.gtmOnSuccess ,  data.gtmOnFailure );
} else {
  addConsentListener( data.consent_type, (consentType, granted) => {
     if (!isTagLoaded && consentType === data.consent_type && granted) {
        loadTag();    
      }    
  });
  data.gtmOnSuccess()
}
```

the loadTag function on line 98 will be called long after the injection of the template, when the user provided his consent thru the web UI, so the tag template is already injected (without the tracking); so first I call addConsentListener function  and right after I should call data.gtmOnSuccess(), but not inside the ConsentListener Function
