### ISSUE TITLE
Need help in publishing our template

### ISSUE THREAD

**Issue by vineetenjoy** [leoschuler/gtag-mautic-initialization#4]
Hey Leo,

We are trying to publish our template to google tag manager gallery. However its not getting published and we not getting any updates from google too.

Can you please help in ways to navigate across this issue and get our template published to gallery?

**Comment by leoschuler** [comment]
I can tell my experience: 

- once I submit the template, I just got a message that the submission was received, there was no way to check that message again and there is not a page that you can see your submission and status.
- they give no estimation to review the tag
- it took me more than a month to get the first feedback: people from google simply open an issue in the repository asking you to update your code based on their analysis, the user that does a revision does not present themself as being from tag manager, they just open an issue, I could only tell this person was doing the revision for tag manager based on their github activity history 
- I recommend you to work on the open issue as soon as possible, deliver the change and close the issue. make sure you document the changes and tie it to the issue
- after that it is another waiting period, other users might raise new issues, but they usually don't comment in the issue you closed,
- after some weeks (maybe months) in that process your tag is published 
- I did not received any notification that the tag template was published, a friend of mine told me when he saw it.

I recommend you to include in the documentation how to manually import your tag, so users can implement it before it is published in the gallery
